interface CacheCreationUsage {
  ephemeral_1h_input_tokens?: number;
  ephemeral_5m_input_tokens?: number;
}

interface TokenUsage {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_input_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_creation?: CacheCreationUsage;
}

function tokenCount(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return 0;
  return value;
}

/** Tokens occupying the context before the current assistant response. */
export function getContextInputTokens(usage: TokenUsage | undefined): number {
  if (!usage) return 0;
  return tokenCount(usage.input_tokens)
    + tokenCount(usage.cache_read_input_tokens)
    + tokenCount(usage.cache_creation_input_tokens)
    + tokenCount(usage.cache_creation?.ephemeral_1h_input_tokens)
    + tokenCount(usage.cache_creation?.ephemeral_5m_input_tokens);
}

/** Output tokens generated by the current model call. */
export function getContextOutputTokens(usage: TokenUsage | undefined): number {
  return tokenCount(usage?.output_tokens);
}
